version: "3.9"

services:
  
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80 

  mysql:
    container_name: ${APP_NAME}_mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    command:
      - '--innodb_buffer_pool_size=${MYSQL_INNODB_BUFFER_POOL_SIZE:-128M}'
    networks:
      - default    

  php:
    container_name: ${APP_NAME}_php
    image: php:fpm-alpine
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./app:/var/www/html  

volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge
